import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css';
import AuthProvider from "@/context/authprovider";
import { EdgeStoreProvider } from "@/lib/edgestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EcommerceApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <EdgeStoreProvider>
            {children}
          </EdgeStoreProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
